### ISSUE TITLE
Can't add Google account using CalyxOS latest stable build on new Pixel 5

### ISSUE THREAD

**Issue by LunchBoxStevieC** [microg/GmsCore#1425]
New Pixel 5, installed latest stable CalyxOS can't add google account.

Tried factory reset and reflash and still won't work.

Gets to I accept, then says sorry there was a problem contacting the server and try again later.

Tried multiple google accounts with 2FA turned off.

**Comment by abu-co** [comment]
The same thing happened on my Huawei MatePad, after accepting _Google Play Terms of Service_, etc.

The only useful log entry I could find is a warning message:
```
GmsAuthLoginBrowser: onException
  java.io.IOException: Error=ServerError
   at org.microg.gms.common.HttpFormClient.request(HttpFormClient.java:95)
   at org.microg.gms.common.HttpFormClient$1.run(HttpFormClient.java:198)
   at java.lang.Thread.run(Thread.java:929)
```

Here's [a screenshot of the error](https://user-images.githubusercontent.com/52994294/112709262-eab3db80-8f0b-11eb-8199-656ee6ce2308.jpg).

**Comment by hyppalectryon** [comment]
having same issue. tried different builds and got same results. tried fresh install, no difference.

**Comment by marissarousseau** [comment]
I am also experiencing this issue on a new Pixel 4 with a fresh install of the most recent version of Calyx OS. My previous device, which is already signed into my Google accounts, works as expected, however.

**Comment by idanoo** [comment]
Same issue here. Have tried every combination of disabling registration/GCM/rebooting, Wifi/Mobile 

There is an issue on CalyxOS Gitlab with recent updates a potential patch for it https://gitlab.com/CalyxOS/calyxos/-/issues/91

**Comment by LunchBoxStevieC** [comment]
I did try the resetting and adding an account before SIM card etc. as described and that didn't work for me.  I'll just have to wait until they push an update to fix it.  Just some minor things not worrying for me without MicroG so it's not a huge deal, just annoying.

**Comment by chirayudesai** [comment]
I think this can be closed now, it was an issue with our downstream implementation of microG.

We released a fix a month ago (by grabbing the Vanced Huawei Login code) which seems to work well for everyone regardless of setup.

It may be related to some properties set in the OS build however we tried changing those (product.brand for example), but it didn't help on existing devices. Vanced worked.

**Comment by gled-rs** [comment]
I do have the same issue on a clean grapheneos install with the 0.2.21.212158 release.

```
07-06 14:33:28.622  3972 20766 W GmsAuthLoginBrowser: onException
07-06 14:33:28.622  3972 20766 W GmsAuthLoginBrowser: java.io.IOException: Error=ServerError
```
after accepting the ToS.


I tried factory reset, clean setup, no registration/gcm service running. Still the same error.

**Comment by xenon205** [comment]
I also coudn't add G account and what did trick for me was to disable microG core and enable it back then i went to microG setting and turned off device registration (it shoud not be regitered), then when i tried to add account everthing went smothly

**Comment by Henry-ZHR** [comment]
> I also coudn't add G account and what did trick for me was to disable microG core , cleare all date stored and enable it back then i went to microG setting and turned off device registration (it shoud not be regitered), then when i tried to add account everthing went smothly

Works for me as well

**Comment by ale5000-git** [comment]
This should be already fixed, for those that still have problems I suggest to update microG GmsCore, clean app data of microG GmsCore and retry.
In case of additional issues please open another ticket.

**Comment by Sn4kez** [comment]
> I also coudn't add G account and what did trick for me was to disable microG core , cleare all date stored and enable it back then i went to microG setting and turned off device registration (it shoud not be regitered), then when i tried to add account everthing went smothly

Thank you so much! This helped me out after countless other try.
