### ISSUE TITLE
[ch.protonmail.android] Protonmail does not register for push notifications

### ISSUE THREAD

**Issue by DangerousDays** [microg/GmsCore#1494]
**Affected app**
Name: Protonmail
Package id: ch.protonmail.android

**Describe the bug**
Google device registration, cloud messaging, and google safetynet are enabled, yet ProtonMail produces no push notifications.

**To Reproduce**
1. Send mail to protonmail address
2. No push notification

**Expected behavior**
I expect a push notification from protonmail app

**Screenshots**

**System**
Android Version: 11
Custom ROM: crDroid 7.6

**microG**
microG Core version: 0.2.19.211515
microG Self-Check results: All ticked

**Additional context**
I have FakeGapps and FakeStore installed for microG. I tried dialing *#*#2432546#*#*, but it did not help. Not sure if I need some specific timing for it.

**Comment by DangerousDays** [comment]
FIXED: I cleared the cached in Protonmail and it registered.

**Comment by DangerousDays** [comment]
I was too quick to comment. It registered after clearing the cache, but I get no notifications.

**Comment by 4n0nym0u53** [comment]
Same problem here on LineageOS for microG running on a OnePlus 8T (latest version from May 8). Tried reinstalling ProtonMail, but no luck. Also tried clearing storage for microG and then reinstall ProtonMail (and all other apps using GCM), still no luck. It works with other GCM dependant apps, so it seems like a ProtonMail specific issue.

**microG**
microG Core version: 0.2.18.204714
microG Self-Check results: All ticked

**Comment by MattRGX** [comment]
i'm on /e/ Q ! Everything is up to date ! Clearing the cache did not solve the problem for me. Protonmail is still not registered in Cloud Messaging.

**Comment by Idesmi** [comment]
I'm having the same problem, same version of Android (LineageOS 18.1) and MicroG. Other apps are able to register and receive notifications.
It used to work before upgrading to Android 11.

**Comment by 4n0nym0u53** [comment]
Update: The issue seems to have fixed itself for me. ProtonMail is now registered and I'm receiving push notifications. Maybe it's because my ROM got updated yesterday, which upgraded microG to version 0.2.19.211515, but I don't think so since that's the version author had problems with too.

**Comment by MattRGX** [comment]
> Update: The issue seems to have fixed itself for me. ProtonMail is now registered and I'm receiving push notifications. Maybe it's because my ROM got updated yesterday, which upgraded microG to version 0.2.19.211515, but I don't think so since that's the version author had problems with too.

Yeah for me too. It's working now. But i didn't do any modification or update since the problem appear. I guess some holy spirit did something... Thanks anyway

**Comment by DangerousDays** [comment]
Works now for whatever reason.
