### ISSUE TITLE
[zoleoinc.zoleo] Zoleo emergency satellite communicator app not working

### ISSUE THREAD

**Issue by WinstonSmith73** [microg/GmsCore#2591]
**Affected app**
Name: Zoleo
Package id: zoleoinc.zoleo

**Describe the bug**
App won't launch. Either freezes on splash logo or just shows white screen. Same issue reported here:
https://gitlab.com/CalyxOS/calyxos/-/issues/2508 and referred to this issue tracker by CalyxOS here: https://www.reddit.com/r/CalyxOS/comments/1fw46ec/comment/lt1sf1g/

**To Reproduce**
1. Launch Zoleo

**Expected behavior**
App launches to full interface for bluetooth pairing and messaging.

**Observed behavior**
App loads splash screen then hangs and eventually quits with "ZOLEO keeps stopping."

**System**
Android Version: 14
Custom ROM: CalyxOS 5.12.0

**microG**
microG Core version: 0.3.2.240913-21 (9f758d8)
microG Self-Check results: All ticked except "Permission to This app can appear on top of other appss" [unabled to tick it]

**Additional context**

**Comment by ale5000-git** [comment]
Maybe the problem was already fixed between version 0.3.2 and 0.3.4.

**Comment by WinstonSmith73** [comment]
It seems that I have two versions of microG installed, so this may be the cause. One was installed as part of YouTube ReVanced:

https://github.com/revanced/gmscore/releases/tag/v0.3.1.4.240913

Uninstalling it didn't fix Zoleo, but that's still my suspicion.

Next time I do a fresh install I'll have to test before installing ReVanced.

**Comment by WinstonSmith73** [comment]
It was the notifications, thank you (and duh). I just figured when I read my messages the dots would clear.

**Comment by WinstonSmith73** [comment]
Zoleo is working again as-of the latest update (just updated). Possible it's also related to updating to Android 15 (CalyxOS 6).
