### ISSUE TITLE
Error getting token from Google when checking Google Play Integrity on Pixel 6 with CalyxOS

### ISSUE THREAD

**Issue by AZthemute** [microg/GmsCore#2758]
**Describe the bug**
After installing the new version of CalyxOS with microG 6.3.0, I tried the Play Integrity API Checker app, which just gives the error "Error getting token from Google: Unknown internal error." I do not have an unlocked bootloader and Magisk is not installed either.

This isn't much information, but I don't know how to get more from the app. If anyone knows how to check easier what the actual issue is, please let me know and I will provide more info.

The specific app I'm using is https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck&hl=en_GB but no apps I've used that require play integrity work either.

In microG's Google SafetyNet page, there no apps listed that are using SafetyNet, despite the fact that I have multiple apps which do use Play Integrity.

**Screenshots**
![Image](https://github.com/user-attachments/assets/3a72cde7-ffc7-4da7-9c86-fa13f327b082)

**System**
Android Version: 15
Custom ROM: CalyxOS 6.3.0
microG version: 0.3.6.244735-27 (e7e4dbc)

Please let me know how to get more information about the specific issue.

**Comment by ale5000-git** [comment]
I'm not completely sure but maybe it is the problem fixed by #2740

**Comment by AZthemute** [comment]
I tried another app, this is what I got:
![Image](https://github.com/user-attachments/assets/0f6906a5-20c7-4945-aaa5-e2ece407fe6f)

And for safetynet:
![Image](https://github.com/user-attachments/assets/384ae40c-0003-4b52-b49e-af42fa44a691)

All combinations of settings give the result.

> I'm not completely sure but maybe it is the problem fixed by [#2740](https://github.com/microg/GmsCore/pull/2740)

No, I'm past that commit. Again, my microG version is 0.3.6.244735-27 (e7e4dbc). I believe this is the version that came with my updated CalyxOS, but just in case, I have the F-Droid repo added too, and F-Droid reports that there are no updates. Can't seem to find commit e7e4dbc though so I'm not sure what's going on there, maybe just a calyx thing?

**Comment by AZthemute** [comment]
> The one linked by me is a pull request not yet merged, so it isn't included unless CalyxOS developers have picked it manually.

Ah, right. Do you know how I can manually update microG on my phone to have that PR? I doubt just installing an APK, even through adb, wouldn't break things.

**Comment by ale5000-git** [comment]
You have to wait it to get merged and then wait for a new version of microG released.

Or alternatively you have to compile it yourself but then the apk would have a different signature and you will have to remove the previous one (so losing all microG settings and GCM registrations) and install your compiled one.

**Comment by AZthemute** [comment]
Earlier I managed to get some information about SafetyNet which may or may not be relevant.
![Image](https://github.com/user-attachments/assets/0761cf0f-a8d3-4a2a-b211-0dd4b88b0b36)
The result in microG has a warning sign saying:

> Attestation: Warning: CTS profile does not match
> Bootloader is not locked

My bootloader is locked and OEM unlocking is disabled in developer settings. Issue persists even after a restart.

> Or alternatively you have to compile it yourself but then the apk would have a different signature and you will have to remove the previous one (so losing all microG settings and GCM registrations) and install your compiled one.

Is it not possible to backup the settings and other data?

**Comment by apex-cmyk** [comment]
### To resolve the issue of "Error getting token from Google: Unknown internal error" when using Play Integrity API Checker on CalyxOS with microG, follow these steps:
**Check microG Settings:**
Open the microG Settings app.
Go to Self-Check and ensure all permissions are granted, especially for Google Cloud Messaging and Google SafetyNet.
Ensure that Device Registration and Google SafetyNet are enabled.
**Update microG:**
Ensure you are using the latest version of microG. If not, update it from the official microG repository or F-Droid.
**Configure Google Account:**
In microG Settings, go to Google Account and ensure your Google account is properly added and synced.
**Check Network Connectivity:**
Ensure your device has a stable internet connection. Play Integrity API requires access to Google servers.
**Reinstall Play Integrity API Checker:**
Uninstall the Play Integrity API Checker app and reinstall it from the Google Play Store or an alternative source.
**Enable Google SafetyNet in microG:**
In microG Settings, go to Google SafetyNet and ensure it is enabled.
If no apps are listed, try restarting your device and checking again.
**Check CalyxOS Configuration:**
Ensure CalyxOS is properly configured to support microG. If necessary, reflash the ROM with the latest version.
**Use Alternative Apps:**
If the issue persists, try using alternative apps that do not rely on Play Integrity API, or use a different ROM that fully supports Google Play Services.

I am working for the Yajuzhen CloudPhone Platform(亚矩阵云手机平台),in china. Welcome to my homepage to communicate together.

**Comment by ale5000-git** [comment]
The #2740 have been merged, so there can be improvements.
