### ISSUE TITLE
Anymote "no billing permission"

### ISSUE THREAD

**Issue by Monk-c** [microg/GmsCore#567]
Hi,
I hope I am right here to contact you.
I flashed to lineageOS for microg.
Everything works fine but one app, "Anymote", doesn't work. It crashes right from the start - "No billing permission, this build is broken".
Is there anything I can do or adjust? Can any1 please try it on his phone :-) ?
I have a Xiaomi Redmi Note 4x, LOS 15.1, the build from lineage.microg.org, 20180703
I tried older versions of "Anymote", but none worked. With MIUI and Play Services, it worked fine.
Thank you for your help!
Monk

**Comment by ArchangeGabriel** [comment]
`No billing permission` means the app is trying to reach the PlayStore (I bet it has in-app purchases). If the app doesn’t work at all without this, you can try to replace the Blank/FakeStore with the real thing. Ask @ale5000-git or @Nanolx for that.

**Comment by Monk-c** [comment]
Hi and ty so much for the answer.

Well... I tried to install just the "Google Play Store" apk, but it doesn't install...
I think, you have to install gapps in general to install the play store? That's what I wanted to avoid^^

The App works without further in-app-purchase, but you can purchase to pro version - but not only via play store, you can buy a license key via paypal, too. But unfortunately, it doesn't open at all.

I found a possibilty to contact Nanolx, but not ale5000... sorry^^ How can I contact him?

Any further tipps?

Thx
Michael

**Comment by ArchangeGabriel** [comment]
No, you don’t have to install PlayServices, they are way to have PlayStore working with μG, and that is what @ale5000-git and @Nanolx do AFAIR. Normally they should both have been notified of this issue since I’ve mentioned them, so I would just wait for them to come and chime in.

**Comment by Nanolx** [comment]
I'll have a look into this, soon™

Am 5. Juli 2018 10:57:11 MESZ schrieb Bruno Pagani <notifications@github.com>:
>No, you don’t have to install PlayServices, they are way to have
>PlayStore working with μG, and that is what @ale5000-git and @Nanolx do
>AFAIR. Normally they should both have been notified of this issue since
>I’ve mentioned them, so I would just wait for them to come and chime
>in.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_GmsCore/issues/567#issuecomment-402653680

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by chris42** [comment]
Wich store for microg did you install? 
Even If you are not using Playstore, you should have fakestore/blankstore installed.
They normally should show availability to the apps for in-app purchases and hence silence errors. However when you trigger in-app purchase nothing should happen.

**Comment by Monk-c** [comment]
I installed both.

I'm experiencing more and more problems. Several apps say: "This app will only work if you update Google Play Services." or similar...
Maybe I did sth. wrong in general? 

Perhaps someone can just test if he can open the App 'TVNOW Plus'.

https://play.google.com/store/apps/details?id=de.rtli.tvnow

**Comment by chris42** [comment]
Hmm... maybe that is the reason for your error with the app, you should only install one. Try to just have fakestore installed and see what happens.

The other errors on "This app will only work if you update Google Play Services." are a different story.
The regular microg versions are currently lacking an update.
Sadly there is only an unofficial update available. You find in the XDA Forum https://forum.xda-developers.com/android/apps-games/app-microg-gmscore-floss-play-services-t3217616/page478

**Comment by Monk-c** [comment]
Hi m8,

TY for your help.

No, I had only FakeStore installed, added BlankStore later as an attempt.

OK, I will try the unofficial update.

**Comment by Monk-c** [comment]
Downloaded the 118 apk, it just says "not installed" :-(

**Comment by Monk-c** [comment]
By the way... If someone would confirm the problems with the two apps I mentioned, that would fine for a start.
The most important question for now is, if I made sth. wrong with the installation or settings of microg4LOS. If someone (more experienced than me lol) has the same problems, I am satisfied :-)

**Comment by chris42** [comment]
The "not installed" is to be expected, as it is compiled from a different repository, hence has a different signature. You would need to put it manually in /system/priv-app by the name GmsCore.apk.
There is some explanation around this in the Forum Thread I sent.

For confirming your application errors, I can't help, as I have a self compiled build within AOSP with updated version numbers. But I am pretty confident, that getting the 118 running should solve the  "This app will only work if you update Google Play Services." message.

**Comment by chris42** [comment]
Not sure, I don't use telegram and without app you are not allowed to take part... :-/

**Comment by Monk-c** [comment]
Sry, found out that the NoGapps Group is the place. I read of a microG group but they likely meant the NoGapps group.

**Comment by Monk-c** [comment]
Ty m8, it worked. Maybe for others:
You have to:
1. root (download su addon from LOS download page (Extras), choose the right Version according to your phone's architecture. Then install the ZIP with TWRP.
2. Activate Developer options (by clicking 7 times in the build no.)
3. download a root Explorer APP. Like amaze from f-droid (you have to make the root files visible in the options).
4. Check the /system/priv-apps/GmsCore.apk for its permissions.
5. Replace the apk with the unofficial GmsCore, set the same permissions.
6. Reboot
Done!

**Comment by Monk-c** [comment]
By the way, the Anymote error still appears ;-) No problem. I will search another app or do without.

**Comment by ale5000-git** [comment]
The solution should be:
- Update FakeStore to v0.2.0
- Update also microG GmsCore to be safer
- Uninstall and reinstall the apps with the issue

Please try and report back.

**Comment by ale5000-git** [comment]
This problem should already be fixed, if you still have the problem report back please.
